### ISSUE TITLE
Delayed job migration doesn't work with rails 5.0.1

### ISSUE THREAD

**Issue by blackjid** [platanus/potassium#125]
I'm getting this error

```
StandardError: An error has occurred, this and all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class CreateDelayedJobs < ActiveRecord::Migration[4.2]
```

**Comment by blackjid** [comment]
I think in the near future we should evaluate to use something different that delayed jobs.
Delayed jobs haven't been updated for a while, and looks unmaintained. Right now is not compatible with rails 5.x

**Comment by blackjid** [comment]
well, this get's wrong beyond the syntaxis of the migration.
If I try to run de worker I get an error.

```
cd tmp/dummy_app
dummy_app|master⚡ ⇒ bundle exec rake jobs:work
[Worker(host:black-mac.lan pid:68103)] Starting job worker
rake aborted!
NoMethodError: undefined method `cleanup!' for ActionDispatch::Reloader:Class
bin/bundle:3:in `load'
bin/bundle:3:in `<main>'
Tasks: TOP => jobs:work
(See full trace by running task with --trace)
```

In rails 5.1 the method `cleanup!` was removed from that class.

Here is an issue about it. There is a ugly workaround and reference to a PR that should solve the problem. https://github.com/collectiveidea/delayed_job/issues/944

I think this is important to solve before merging #127

**Comment by llekn** [comment]
Solved in commit f8a69a1 , which is included in #127

**Comment by blackjid** [comment]
as I mention in slack, this evolved differently, is not only an issue with the version of the migration.

**Comment by llekn** [comment]
Oh, I see.

I think it would be nice to explore alternatives to `delayed_jobs` as it seems it is not being maintained anymore.

Any suggestions?

**Comment by blackjid** [comment]
We've been using https://github.com/mperham/sidekiq in a couple of projects...

It uses redis as a backend to manage the queue, so it will make us need another piece in our deployments. That being said, we can use heroku-redis, there is a free version that should fit our most common needs.

@ldlsegovia had experience using sidekiq, he might want to give his point of view.

**Comment by ldlsegovia** [comment]
I think sidekiq is a good choice because:

* It's faster than delayed_job https://github.com/mperham/sidekiq#performance
* We can run multiple jobs in the same worker using threads.
* It offers a nice app to get some information about jobs.

I've made a PR #133 including this alternative.

**Comment by blackjid** [comment]
awesome, also I think is super flexible and the community is super active, there ara a lot of extensions out there
